[project]
name = "paddleocr-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.129.0",
    "paddleocr==3.3.2",
    "paddlepaddle==3.2.2",
    "python-multipart>=0.0.22",
    "uvicorn>=0.41.0",
]
